#ifndef CARTESIAN_ADMITTANCE_CONTROLLER__VISIBILITY_CONTROL_H_
#define CARTESIAN_ADMITTANCE_CONTROLLER__VISIBILITY_CONTROL_H_

// This logic was borrowed (then namespaced) from the examples on the gcc wiki:
//     https://gcc.gnu.org/wiki/Visibility

#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define CARTESIAN_ADMITTANCE_CONTROLLER_EXPORT __attribute__ ((dllexport))
    #define CARTESIAN_ADMITTANCE_CONTROLLER_IMPORT __attribute__ ((dllimport))
  #else
    #define CARTESIAN_ADMITTANCE_CONTROLLER_EXPORT __declspec(dllexport)
    #define CARTESIAN_ADMITTANCE_CONTROLLER_IMPORT __declspec(dllimport)
  #endif
  #ifdef CARTESIAN_ADMITTANCE_CONTROLLER_BUILDING_LIBRARY
    #define CARTESIAN_ADMITTANCE_CONTROLLER_PUBLIC CARTESIAN_ADMITTANCE_CONTROLLER_EXPORT
  #else
    #define CARTESIAN_ADMITTANCE_CONTROLLER_PUBLIC CARTESIAN_ADMITTANCE_CONTROLLER_IMPORT
  #endif
  #define CARTESIAN_ADMITTANCE_CONTROLLER_PUBLIC_TYPE CARTESIAN_ADMITTANCE_CONTROLLER_PUBLIC
  #define CARTESIAN_ADMITTANCE_CONTROLLER_LOCAL
#else
  #define CARTESIAN_ADMITTANCE_CONTROLLER_EXPORT __attribute__ ((visibility("default")))
  #define CARTESIAN_ADMITTANCE_CONTROLLER_IMPORT
  #if __GNUC__ >= 4
    #define CARTESIAN_ADMITTANCE_CONTROLLER_PUBLIC __attribute__ ((visibility("default")))
    #define CARTESIAN_ADMITTANCE_CONTROLLER_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define CARTESIAN_ADMITTANCE_CONTROLLER_PUBLIC
    #define CARTESIAN_ADMITTANCE_CONTROLLER_LOCAL
  #endif
  #define CARTESIAN_ADMITTANCE_CONTROLLER_PUBLIC_TYPE
#endif

#endif  // CARTESIAN_ADMITTANCE_CONTROLLER__VISIBILITY_CONTROL_H_
