name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - name: Prepare
        run: |
          mkdir -p ${{github.workspace}}/src
      - uses: actions/checkout@v4
        with:
          path: src/cartesian_controllers_ros2

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          tags: cartesian_controllers_ros2:humble
          file: .docker/ci/Dockerfile
          push: false

      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          image: cartesian_controllers_ros2:humble
          options: -v ${{github.workspace}}/:/ros/
          run: |
            cd /ros # structure = <...>/ros/src/cartesian_controllers_ros2/<...>
            . /opt/ros/humble/setup.sh
            vcs import src < src/cartesian_controllers_ros2/cartesian_controllers_ros2.repos
            rosdep install --ignore-src --from-paths . -y -r
            colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --symlink-install

      - name: Tests
        uses: addnab/docker-run-action@v3
        with:
          image: cartesian_controllers_ros2:humble
          options: -v ${{github.workspace}}/:/ros/
          run: |
            cd /ros
            . /opt/ros/humble/setup.sh
            vcs import src < src/cartesian_controllers_ros2/cartesian_controllers_ros2.repos
            rosdep install --ignore-src --from-paths . -y -r
            colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --symlink-install
            colcon test --event-handlers console_direct+
            colcon test-result

      - name: Upload Tests to Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: build/*/test_results/*/*.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/*/test_results/*/*.xml
